name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
     env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true' # Suppresses the warning by forcing Node 24 natively

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI with NPM
        run: |
          npm install @salesforce/cli --global

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" | sf org login sfdx-url --alias nexusOrg --set-default-dev-hub --sfdx-url-stdin

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --target-org nexusOrg --wait 30
